spring.application.name=lunarivet-api

server.port=8080

# POSTGRES

spring.datasource.url=jdbc:postgresql://localhost:5432/lunarivet
spring.datasource.username=postgres
spring.datasource.password=yanes674320
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Pode remover; Hibernate detecta sozinho
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT

jwt.secret=LunarivetJwtSecretKeyMuitoGrandeTroqueDepoisParaProducao123456789ABCDEF
jwt.expiration=86400000

# EMAIL

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=SEU_EMAIL@gmail.com
spring.mail.password=SENHA_APP_GOOGLE

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# MULTIPART

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# LOGS

logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.lunarivet=DEBUG

# JACKSON

spring.jackson.serialization.fail-on-empty-beans=false

# SCHEDULER

spring.task.scheduling.pool.size=5